name: carbon
description: A new Flutter project to calculate digital carbon footprint and provide e-waste awareness.

publish_to: 'none' # Prevent publishing to pub.dev

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.3 # For state management
  location: ^7.0.1 # For getting nearby centers

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true